url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
socials:
  - title: 'LinkedIn'
    url: '#'
    image_path: 'assets/images/linkedin.png'
  - title: 'Instagram'
    url: '#'
    image_path: 'assets/images/instagram.png'
  - title: 'GitHub'
    url: '#'
    image_path: 'assets/images/github.png'

